### ISSUE TITLE
tur: Ada penjelasan kalimat yang belum diterjemahkan

### ISSUE THREAD

**Issue by bryantobing12** [golang-id/tour#1]
Konteks: https://go-tour-id2.appspot.com/moretypes/16

Seharusnya saya pilih dokumentasi Bahasa Indonesia tetapia ada Bahasa yang belum diterjemahkan ke Bahasa Indonesia dan masih menggunakan Bahasa inggris

**Comment by shuLhan** [comment]
> On 10 Feb 2020, at 11.23, Bryan Lumbantobing <notifications@github.com> wrote:
> 
> Konteks: https://go-tour-id2.appspot.com/moretypes/16
> 
> Seharusnya saya pilih dokumentasi Bahasa Indonesia tetapia ada Bahasa yang belum diterjemahkan ke Bahasa Indonesia dan masih menggunakan Bahasa inggris
> 

Ok, terima kasih atas masukannya.

**Comment by shuLhan** [comment]
@bryantobing12 Sudah diperbaiki ya. Silahkan diperiksa kembali.
